production:
  hostname: shaadi.yourdomain.com
  user: frappe
  site_name: shaadi.yourdomain.com
  deploy_path: /home/frappe/shaadi-prod

staging:
  hostname: staging.shaadi.yourdomain.com
  user: frappe
  site_name: staging.shaadi.yourdomain.com
  deploy_path: /home/frappe/shaadi-staging

develop:
  hostname: dev.shaadi.yourdomain.com
  user: frappe
  site_name: dev.shaadi.yourdomain.com
  deploy_path: /home/frappe/shaadi-dev
