/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterPanel: typeof import('./src/components/FilterPanel.vue')['default']
    MatchModal: typeof import('./src/components/MatchModal.vue')['default']
    MatchPercentage: typeof import('./src/components/MatchPercentage.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PreferenceSetupModal: typeof import('./src/components/PreferenceSetupModal.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwipeCard: typeof import('./src/components/SwipeCard.vue')['default']
    SwipeStack: typeof import('./src/components/SwipeStack.vue')['default']
  }
}
